window.RUTA_DATA={
meta:{title:'Ruta Perú',reviewed:'19 de agosto de 2026',reviewISO:'2026-08-19',note:'Contenido educativo revisado con fuentes oficiales. Las fuentes originales quedan disponibles como respaldo opcional.'},
nav:[
 {group:'Aprender',items:[['home','⌂','Inicio'],['moto','◉','Motocicleta'],['auto','▣','Automóvil'],['signs','◇','Señales'],['rules','↗','Reglas generales']]},
 {group:'Practicar',items:[['cases','◈','Casos prácticos'],['quiz','✓','Evaluación'],['errors','!','Mis errores'],['favorites','☆','Favoritos']]},
 {group:'Referencia',items:[['infractions','△','Infracciones'],['sources','ⓘ','Fuentes oficiales'],['progress','◌','Mi progreso']]}
],
sources:{
 ds018:{title:'Cascos, lentes y chalecos para motociclistas',norm:'D.S. N.° 018-2025-MTC',entity:'Ministerio de Transportes y Comunicaciones',date:'8 de noviembre de 2025',status:'Vigente · verificado',url:'https://www.gob.pe/institucion/mtc/normas-legales/7380666-018-2025-mtc',refs:['Artículo 105.1','Artículo 105.2','G.59','G.68','G.69'],digest:['Modifica el Reglamento Nacional de Tránsito respecto del uso de casco, lentes protectores y chaleco en motocicletas.','Cuando el casco no cuenta con visor, corresponde el uso de lentes protectores.','La infracción G.59 es grave y equivale al 8 % de la UIT, 40 puntos y retención del vehículo.','Las sanciones G.68 y G.69 vinculadas al chaleco se aplican en lugares declarados en estado de emergencia por orden interno cuando la declaratoria lo disponga expresamente. El minicurso separa esta regla sancionadora del texto del artículo 105.2 para evitar simplificaciones.']},
 rd0012:{title:'Especificaciones técnicas para casco y chaleco',norm:'R.D. N.° 0012-2025-MTC/18',entity:'Ministerio de Transportes y Comunicaciones',date:'20 de junio de 2025',status:'Vigente con modificaciones',url:'https://www.gob.pe/institucion/mtc/normas-legales/6958752-0012-2025-mtc-18',refs:['Anexo I','Anexo II'],digest:['Aprueba las especificaciones técnicas para el uso de cascos de seguridad de conductores y acompañantes de motocicletas.','Deroga la R.D. N.° 008-2025-MTC/18.','Debe leerse junto con sus modificaciones posteriores, entre ellas la R.D. N.° 0028-2025-MTC/18.']},
 rd0028:{title:'Actualización de las especificaciones de cascos',norm:'R.D. N.° 0028-2025-MTC/18',entity:'Ministerio de Transportes y Comunicaciones',date:'25 de noviembre de 2025',status:'Vigente · verificado',url:'https://www.gob.pe/institucion/mtc/normas-legales/7485473-0028-2025-mtc-18',refs:['Anexo I modificado'],digest:['Modifica el Anexo I de la R.D. N.° 0012-2025-MTC/18.','La actualización oficial reconoce cascos integral, modular, cross/off-road y abierto/jet, siempre que cumplan una certificación admitida.','La actualización permite visores o lentes polarizados dentro de las condiciones técnicas aplicables.']},
 casco2026:{title:'Guía Casco Seguro 2026',norm:'Orientación oficial del MTC',entity:'Ministerio de Transportes y Comunicaciones',date:'21 de julio de 2026',status:'Recomendación de seguridad',url:'https://www.gob.pe/institucion/mtc/noticias/1421459-mtc-presenta-la-guia-de-uso-de-casco-seguro-para-motociclistas-en-peru-para-promover-una-conduccion-mas-segura',refs:['Guía Casco Seguro'],digest:['El MTC recuerda que conductor y pasajero deben usar casco con certificación aceptada.','Entre las certificaciones citadas por el MTC figuran ECE 22.05, ECE 22.06 y DOT.','Como recomendación de seguridad, el MTC aconseja reemplazar el casco después de un impacto fuerte aunque no se observen daños.']},
 licenseB:{title:'Clasificación de licencias Clase B',norm:'Reglamento del Sistema de Emisión de Licencias',entity:'Ministerio de Transportes y Comunicaciones',date:'Consulta 2026',status:'Vigente · verificado',url:'https://portal.mtc.gob.pe/transportes/terrestre/licencias/info_general_clasificacion_licencias.html',refs:['Clase B','Categoría II-B'],digest:['La licencia B-IIb autoriza a conducir vehículos L3 y L4 destinados al transporte particular de pasajeros o mercancías.','L3 corresponde a motocicletas de dos ruedas y L4 a motocicletas con sidecar.','La categoría B-IIb también comprende los vehículos autorizados por B-IIa.']},
 licenseA:{title:'Clasificación de licencias Clase A',norm:'Reglamento del Sistema de Emisión de Licencias',entity:'Ministerio de Transportes y Comunicaciones',date:'Consulta 2026',status:'Vigente · verificado',url:'https://www.gob.pe/262-tipos-de-licencia-de-conducir-brevete',refs:['Clase A','Categoría I'],digest:['La licencia A-I es la categoría común para automóviles de uso particular.','Comprende vehículos particulares como sedanes, hatchbacks, station wagon, SUV, pickup y furgones dentro de la clasificación aplicable.']},
 art91:{title:'Documentos que puede requerir la autoridad de tránsito',norm:'Reglamento Nacional de Tránsito · artículo 91',entity:'Reglamento Nacional de Tránsito / Gobierno Regional del Callao',date:'Texto consultado en 2026',status:'Vigente · verificado',url:'https://web.regioncallao.gob.pe/transportes-y-comunicaciones/derecho-de-los-conductores/',refs:['Artículo 91'],digest:['El artículo 91 contempla documento de identidad, licencia de conducir vigente correspondiente al vehículo, tarjeta de identificación vehicular y certificado de inspección técnica vehicular cuando corresponda.','También contempla el SOAT físico vigente; si se cuenta con SOAT electrónico, su contratación y vigencia se verifica en la base de datos correspondiente.']},
 ds011:{title:'Actualización del RNT: control, velocidad y estacionamiento',norm:'D.S. N.° 011-2026-MTC',entity:'Ministerio de Transportes y Comunicaciones',date:'21 de abril de 2026',status:'Vigente · verificado',url:'https://www.gob.pe/institucion/mtc/normas-legales/8042204-011-2026-mtc',refs:['Artículo 57','Artículo 90','Artículo 168-A','Artículo 215'],digest:['Las indicaciones del efectivo de la PNP asignado al control del tránsito prevalecen sobre los semáforos; los semáforos prevalecen sobre otros dispositivos.','El artículo 168-A establece con carácter general un margen de tolerancia de 5 km/h para la supervisión de velocidades máximas. Esto es tolerancia de fiscalización, no un nuevo límite de velocidad.','Actualiza las prohibiciones de estacionamiento previstas en el artículo 215.']},
 speed:{title:'Límites máximos de velocidad en zona urbana',norm:'D.S. N.° 025-2021-MTC',entity:'Ministerio de Transportes y Comunicaciones',date:'Vigentes desde el 18 de julio de 2022',status:'Vigente · verificado',url:'https://www.gob.pe/26617-nuevos-limites-de-velocidad-en-zonas-urbanas-a-nivel-nacional',refs:['Límites urbanos'],digest:['En calles y jirones: máximo 30 km/h.','En avenidas: máximo 50 km/h.','En carreteras que cruzan zonas comerciales, escolares u hospitales: 30 km/h; en zonas residenciales: 50 km/h.','La señalización reguladora específica de la vía también debe respetarse.']},
 ds002:{title:'Restricciones de tránsito durante estados de emergencia',norm:'D.S. N.° 002-2026-MTC',entity:'Ministerio de Transportes y Comunicaciones',date:'15 de enero de 2026',status:'Vigente · verificado',url:'https://www.gob.pe/institucion/mtc/normas-legales/7625120-002-2026-mtc',refs:['Artículo 140-B','M41'],digest:['Incorpora el artículo 140-B al Reglamento Nacional de Tránsito.','Una declaratoria de estado de emergencia por orden interno puede establecer restricciones específicas al tránsito y uso de vehículos en la vía pública.','Las medidas concretas dependen de la declaratoria vigente, por lo que esta parte debe revisarse cuando cambie un estado de emergencia.']},
 motoMTC:{title:'Reglas de circulación segura para motociclistas',norm:'Orientación oficial basada en el RNT',entity:'Ministerio de Transportes y Comunicaciones',date:'1 de febrero de 2024',status:'Orientación oficial',url:'https://www.gob.pe/institucion/mtc/noticias/900548-mtc-exhorta-a-motociclistas-a-cumplir-reglamento-nacional-de-transito-para-prevenir-siniestros-viales-con-consecuencias-fatales',refs:['Orientación MTC'],digest:['El MTC recuerda que la motocicleta debe circular ocupando un carril completo y no debe invadir ciclovías ni veredas.','También recuerda restricciones de adelantamiento cuando la señalización lo prohíbe, al ingresar a una intersección, al aproximarse o atravesar un cruce a nivel y en puentes, viaductos o túneles.']},
 signals:{title:'Manual de Dispositivos de Control de Tránsito Automotor',norm:'R.D. N.° 26-2024-MTC/18',entity:'Ministerio de Transportes y Comunicaciones',date:'16 de octubre de 2024',status:'Manual vigente · verificado',url:'https://www.gob.pe/institucion/mtc/normas-legales/6150395-26-2024-mtc-18',refs:['Manual 2024'],digest:['Aprueba la actualización del Manual de Dispositivos de Control de Tránsito Automotor.','Incluye señales verticales, señales horizontales o demarcaciones y dispositivos para casos especiales.','Organiza diseños de señales reglamentarias, preventivas e informativas y deroga el manual aprobado en 2016.']},
 uit2026:{title:'Valor de la UIT 2026',norm:'D.S. N.° 301-2025-EF',entity:'Ministerio de Economía y Finanzas',date:'17 de diciembre de 2025',status:'Vigente para 2026',url:'https://www.gob.pe/institucion/mef/normas-legales/7540449-301-2025-ef',refs:['UIT 2026'],digest:['La UIT para 2026 es S/ 5 500.','Una sanción equivalente al 8 % de la UIT corresponde a S/ 440 durante 2026.']}
},
modules:{
 moto:{title:'Motocicleta',subtitle:'Primero, lo que realmente usas al conducir.',description:'Licencia, documentos, casco, pasajero, carril, adelantamiento, velocidad y situaciones reales.',tone:'green'},
 auto:{title:'Automóvil',subtitle:'Prepárate desde ahora para conducir un auto.',description:'Licencia A-I y reglas que comparten automóvil y motocicleta.',tone:'blue'},
 signs:{title:'Señales de tránsito',subtitle:'Reconoce antes de memorizar.',description:'Estructura del manual vigente: reglamentarias, preventivas, informativas y marcas viales.',tone:'peach'},
 rules:{title:'Reglas generales',subtitle:'Decisiones que se repiten todos los días.',description:'Autoridad, semáforos, velocidad, estados de emergencia y conducción preventiva.',tone:'violet'},
 infractions:{title:'Infracciones',subtitle:'Sanciones solo cuando están verificadas.',description:'Base inicial de infracciones con monto calculado usando la UIT vigente de 2026.',tone:'rose'}
},
lessons:[
 {id:'moto-license',module:'moto',title:'¿Qué licencia corresponde a una motocicleta?',status:'norm',sources:['licenseB'],summary:'Para una motocicleta L3 de uso particular, la referencia de clasificación es la licencia Clase B, categoría II-B.',steps:{law:'La categoría B-IIb autoriza vehículos L3 y L4 destinados al transporte particular de pasajeros o mercancías.',meaning:'Una licencia para automóvil no reemplaza automáticamente la licencia correspondiente a motocicleta.',practice:'Comprueba en tu licencia la clase, categoría y vigencia antes de conducir.',example:'Una motocicleta convencional de dos ruedas pertenece a la categoría vehicular L3.',mistake:'Pensar que cualquier brevete vigente autoriza cualquier vehículo.'},practice:'Antes de prestar o cambiar de motocicleta, revisa que su categoría vehicular sea compatible con tu licencia.',warning:'Para transporte público o categorías distintas pueden existir requisitos adicionales.',quiz:{q:'¿Qué categoría de licencia autoriza, entre otros, una motocicleta L3 de uso particular?',options:['A-I','B-IIb','B-IIa','A-IIa'],answer:1,why:'La clasificación oficial del MTC ubica L3 y L4 de uso particular en la categoría B-IIb.'}},
 {id:'moto-docs',module:'moto',title:'Documentos durante una intervención',status:'norm',sources:['art91'],summary:'El Reglamento Nacional de Tránsito establece los documentos que puede requerir el efectivo asignado al control del tránsito.',steps:{law:'El artículo 91 contempla identidad, licencia vigente adecuada, tarjeta de identificación vehicular, CITV cuando corresponda y SOAT/CAT según el caso.',meaning:'No todos los documentos se presentan necesariamente en papel: el SOAT electrónico puede verificarse en la base correspondiente.',practice:'Antes de salir, confirma vigencia de licencia y seguro y que los datos del vehículo sean correctos.',example:'Si tu SOAT es electrónico, su contratación y vigencia pueden verificarse digitalmente.',mistake:'Confiar en una fotografía antigua sin revisar la vigencia real.'},practice:'Ten ubicados tus documentos y accesos digitales para no buscarlos durante una intervención.',warning:'El CITV se exige según corresponda; depende del régimen aplicable al vehículo.'},
 {id:'moto-helmet',module:'moto',title:'Casco certificado: qué exige hoy la norma',status:'norm',sources:['ds018','rd0012','rd0028','casco2026'],summary:'Conductor y acompañante deben usar casco; para motocicletas, el casco debe cumplir las especificaciones técnicas vigentes.',steps:{law:'El artículo 105 remite a las especificaciones del MTC. La R.D. N.° 0012-2025-MTC/18 fue modificada posteriormente por la R.D. N.° 0028-2025-MTC/18.',meaning:'No basta cualquier protección de cabeza: el casco debe cumplir una certificación admitida y las especificaciones aplicables.',practice:'Revisa certificación, integridad, talla y sistema de retención antes de usarlo.',example:'El MTC reconoce cascos integral, modular, cross/off-road y abierto/jet cuando cumplen certificación aceptada.',mistake:'Usar casco de bicicleta, industrial, decorativo, sin certificación o estructuralmente dañado.'},practice:'Al comprar, prioriza certificación verificable y ajuste correcto antes que la apariencia.',warning:'La R.D. N.° 008-2025-MTC/18 fue derogada; no debe usarse como fuente vigente.',quiz:{q:'Si el casco no tiene visor, ¿qué exige la regla vigente?',options:['Nada adicional','Lentes protectores','Solo una mica de noche','Únicamente el pasajero usa lentes'],answer:1,why:'El artículo 105 modificado contempla lentes protectores cuando el casco no tiene visor.'}},
 {id:'moto-visor',module:'moto',title:'Visor y lentes: la regla fue actualizada',status:'norm',sources:['ds018','rd0028'],summary:'Las reglas técnicas de 2025 actualizaron el tratamiento de visores y lentes, por lo que ya no es correcto repetir información anterior sin revisar la modificación.',steps:{law:'El D.S. N.° 018-2025-MTC regula visor/lentes y la R.D. N.° 0028-2025-MTC/18 actualiza las especificaciones técnicas.',meaning:'La actualización permite visores o lentes polarizados dentro de las condiciones técnicas aplicables.',practice:'Elige una solución compatible con el casco y que mantenga visibilidad suficiente para la iluminación real.',example:'Una solución permitida durante el día puede no ser prudente para conducción nocturna.',mistake:'Seguir una publicación anterior a noviembre de 2025 como si no hubiera sido modificada.'},practice:'Si el trayecto continuará de noche, usa protección ocular que no reduzca peligrosamente la visibilidad.',warning:'Que una característica esté permitida no significa que sea segura en cualquier condición de luz.'},
 {id:'moto-chaleco',module:'moto',title:'Chaleco con placa: obligación y sanción',status:'norm',sources:['ds018','ds002'],summary:'La regulación debe leerse con cuidado: el D.S. N.° 018-2025-MTC focaliza la aplicación de las sanciones G.68 y G.69 en determinados estados de emergencia.',steps:{law:'Las sanciones por chaleco se aplican en lugares declarados en estado de emergencia por orden interno cuando la declaratoria correspondiente lo dispone expresamente.',meaning:'No es correcto resumir la situación como “se multa igual en todo el Perú”.',practice:'Si estás en una zona con estado de emergencia, revisa la declaratoria vigente y sus restricciones concretas.',example:'Una medida puede activarse en una zona y no en otra según la declaratoria aplicable.',mistake:'Confundir una norma permanente con una medida que depende de una declaratoria temporal.'},practice:'Revisa este punto antes de viajar a otra ciudad cuando haya estados de emergencia vigentes.',warning:'Los estados de emergencia cambian; esta parte necesita revisión periódica.'},
 {id:'moto-lane',module:'moto',title:'La motocicleta ocupa un carril completo',status:'recommendation',sources:['motoMTC'],summary:'El MTC recuerda que la motocicleta circula ocupando un carril completo y no debe invadir ciclovías ni veredas.',steps:{law:'La orientación oficial del MTC aplica las reglas del RNT a la circulación de motocicletas.',meaning:'La motocicleta debe integrarse al tránsito de forma visible y predecible.',practice:'Mantén una posición de carril que te permita ser visto y conservar margen de reacción.',example:'En tráfico lento, zigzaguear por espacios estrechos reduce el tiempo disponible para responder a una puerta, giro o cambio de carril.',mistake:'Circular por una ciclovía solo porque la motocicleta cabe físicamente.'},practice:'Busca visibilidad y espacio de escape antes que ganar unos segundos.',warning:'Esta ficha incluye orientación de seguridad del MTC; no toda recomendación práctica equivale por sí sola a una infracción tipificada.'},
 {id:'moto-overtake',module:'moto',title:'Adelantamientos: zonas de especial riesgo',status:'recommendation',sources:['motoMTC'],summary:'El MTC recuerda restricciones de adelantamiento en intersecciones, cruces a nivel, puentes, viaductos, túneles y donde la señalización lo prohíbe.',steps:{law:'La orientación oficial remite a las reglas del RNT sobre adelantamiento.',meaning:'Hay lugares donde el campo visual o el espacio de maniobra hacen especialmente peligroso intentar adelantar.',practice:'Antes de adelantar, confirma señalización, visibilidad, trayectoria del otro vehículo y espacio para reincorporarte.',example:'No inicies un adelantamiento justo cuando estás entrando a una intersección.',mistake:'Pensar que por ser angosta la motocicleta puede adelantar en cualquier lugar.'},practice:'Si la maniobra exige que otro conductor “te haga espacio”, probablemente ya estás consumiendo un margen de seguridad que necesitas.',warning:'Respeta siempre la señalización específica existente en la vía.'},
 {id:'moto-speed',module:'moto',title:'Velocidad urbana y tolerancia de fiscalización',status:'norm',sources:['speed','ds011'],summary:'En calles y jirones el máximo general es 30 km/h y en avenidas 50 km/h. El margen general de 5 km/h introducido en 2026 es una tolerancia de supervisión, no un nuevo límite.',steps:{law:'El D.S. N.° 025-2021-MTC fijó 30 km/h en calles/jirones y 50 km/h en avenidas; el D.S. N.° 011-2026-MTC incorporó el artículo 168-A sobre tolerancia de fiscalización.',meaning:'Una avenida no pasa a tener límite de 55 km/h: el límite sigue siendo 50 km/h.',practice:'Conduce tomando como referencia el límite real y la señalización, no intentando “consumir” el margen de fiscalización.',example:'En una avenida sin otra señal específica, la referencia general es 50 km/h.',mistake:'Sumar automáticamente 5 km/h al límite y tratar el resultado como una nueva velocidad permitida.'},practice:'Con lluvia, congestión o poca visibilidad puede ser prudente circular por debajo del máximo.',warning:'Un límite máximo no obliga a mantener esa velocidad si las condiciones no son seguras.',quiz:{q:'En una avenida urbana, ¿qué representa el margen general de 5 km/h del artículo 168-A?',options:['Un nuevo límite de 55 km/h','Una tolerancia de supervisión','Una velocidad mínima','Una excepción solo para motos'],answer:1,why:'El límite general permanece en 50 km/h; el margen de 5 km/h se refiere a la supervisión o fiscalización.'}},
 {id:'rules-police',module:'rules',title:'PNP, semáforo y señales: ¿qué prevalece?',status:'norm',sources:['ds011'],summary:'La actualización de 2026 establece una jerarquía clara para resolver instrucciones contradictorias en la vía.',steps:{law:'Las indicaciones del efectivo PNP asignado al control del tránsito prevalecen sobre el semáforo; el semáforo prevalece sobre otros dispositivos.',meaning:'Una luz verde no autoriza a continuar si un efectivo de tránsito te ordena detenerte.',practice:'Reduce velocidad y sigue la instrucción del efectivo cuando esté dirigiendo el tránsito.',example:'Semáforo verde + efectivo indicando “alto”: debes detenerte.',mistake:'Mirar solo el semáforo e ignorar al efectivo que está controlando la intersección.'},practice:'En intersecciones intervenidas, busca primero las señales manuales del efectivo.',warning:'La indicación debe provenir del efectivo asignado al control del tránsito.',quiz:{q:'Semáforo en verde, pero el efectivo PNP de tránsito ordena detenerte. ¿Qué haces?',options:['Avanzo porque el verde prevalece','Me detengo','Toco claxon y avanzo','Solo me detengo si hay peatones'],answer:1,why:'El artículo 57 modificado dispone que la indicación del efectivo PNP de tránsito prevalece sobre el semáforo.'}},
 {id:'rules-emergency',module:'rules',title:'Estados de emergencia y restricciones vehiculares',status:'norm',sources:['ds002'],summary:'Desde 2026 el RNT contempla expresamente restricciones específicas de tránsito y uso de vehículos cuando una declaratoria de emergencia así lo establezca.',steps:{law:'El artículo 140-B permite que la declaratoria establezca restricciones específicas.',meaning:'No existe una única restricción automática para todo estado de emergencia: hay que leer la declaratoria vigente.',practice:'Antes de conducir en una zona bajo emergencia, confirma horario, vehículos comprendidos y alcance territorial.',example:'Una declaratoria puede imponer una restricción nocturna y otra no hacerlo.',mistake:'Aplicar a tu ciudad una medida que corresponde a otra declaratoria.'},practice:'Esta es una de las fichas que debe revisarse con mayor frecuencia.',warning:'La app no afirma que exista hoy una restricción concreta en tu zona sin revisar la declaratoria correspondiente.'},
 {id:'auto-license',module:'auto',title:'Licencia A-I: punto de partida para automóvil',status:'norm',sources:['licenseA'],summary:'La licencia A-I es la categoría habitual para conducir automóviles particulares dentro de la clasificación aplicable.',steps:{law:'La clasificación oficial del MTC ubica en A-I los vehículos particulares comprendidos en las categorías permitidas.',meaning:'Es la referencia básica para sedanes, hatchbacks, SUV, pickup y otros vehículos particulares comprendidos.',practice:'Cuando adquieras un vehículo, revisa su categoría en la tarjeta de identificación y confirma que tu licencia lo autorice.',example:'Un automóvil particular convencional se estudia inicialmente dentro de A-I.',mistake:'Elegir la licencia por el tamaño aparente del vehículo y no por su clasificación.'},practice:'Aprende primero las reglas generales: prioridad, señales, velocidad y estacionamiento se aplican mucho antes de memorizar infracciones.',warning:'Vehículos o servicios especiales pueden requerir categorías superiores.'},
 {id:'signs-structure',module:'signs',title:'Cómo organiza las señales el manual vigente',status:'norm',sources:['signals'],summary:'El Manual 2024 organiza señales verticales, demarcaciones y otros dispositivos; dentro de las verticales se trabajan señales reglamentarias, preventivas e informativas.',steps:{law:'La R.D. N.° 26-2024-MTC/18 aprobó la actualización del Manual de Dispositivos de Control de Tránsito Automotor.',meaning:'No conviene aprender señales como dibujos aislados: cada familia comunica una función distinta.',practice:'Primero identifica la familia; luego el significado específico.',example:'Una señal reglamentaria comunica una regulación; una preventiva alerta sobre un riesgo o condición de la vía.',mistake:'Memorizar solo el color sin comprender la función de la señal.'},practice:'En las siguientes etapas se incorporarán fichas visuales fieles al manual oficial.',warning:'Las imágenes de señales se añadirán únicamente después de cotejarlas con el manual vigente.'}
],
cases:[
 {id:'case-police',title:'Verde, pero el policía te detiene',module:'rules',text:'Llegas a una intersección. El semáforo está en verde, pero un efectivo de la PNP asignado al control del tránsito te indica detenerte.',q:'¿Qué acción corresponde?',options:['Continuar por tener luz verde','Detenerte y seguir la indicación del efectivo','Esperar a que otro vehículo decida','Tocar claxon para confirmar'],answer:1,why:'La indicación del efectivo PNP asignado al control del tránsito prevalece sobre el semáforo.',source:'ds011'},
 {id:'case-visor',title:'Casco certificado sin visor',module:'moto',text:'Vas a salir en motocicleta con un casco certificado que no tiene visor instalado.',q:'¿Qué requisito adicional aplica?',options:['Ninguno','Lentes protectores','Solo llevar una mica guardada','Un chaleco en cualquier lugar del país'],answer:1,why:'La regla vigente contempla lentes protectores cuando el casco no tiene visor.',source:'ds018'},
 {id:'case-speed',title:'Avenida urbana despejada',module:'moto',text:'Circulas por una avenida urbana sin señal reguladora que indique otro límite. La vía está despejada.',q:'¿Cuál es el límite máximo general?',options:['30 km/h','50 km/h','55 km/h','60 km/h'],answer:1,why:'El límite máximo general en avenidas urbanas es 50 km/h. La tolerancia de fiscalización no modifica ese límite.',source:'speed'}
],
infractions:[
 {code:'G.59',title:'Casco/lentes en vehículos de categoría L no cabinados',level:'Grave',sanction:'8 % UIT',amount2026:'S/ 440',points:'40 puntos',measure:'Retención del vehículo',source:'ds018',note:'La tipificación exacta debe leerse junto al cuadro vigente y a las especificaciones técnicas aplicables.'},
 {code:'G.68 / G.69',title:'Chaleco distintivo en el ámbito previsto por la norma',level:'Grave',sanction:'8 % UIT',amount2026:'S/ 440',points:'20 puntos',measure:'Retención del vehículo',source:'ds018',note:'La aplicación de estas sanciones está focalizada en lugares declarados en estado de emergencia cuando la declaratoria lo dispone expresamente.'}
]
};